### ISSUE TITLE
Add support for Permissions

### ISSUE THREAD

**Issue by jainishshah17** [jainishshah17/artifactory-client-node#2]

**Comment by ya2s** [comment]
When will this be implemented?

**Comment by jainishshah17** [comment]
I will start working on it soon.

**Comment by jainishshah17** [comment]
https://github.com/jainishshah17/artifactory-client-node/tree/v0.0.10

**Comment by jainishshah17** [comment]
https://github.com/jainishshah17/artifactory-client-node/tree/v0.0.10

**Comment by ya2s** [comment]
Thanks for your work😊
